galaxy_info:
  author: Roger Lindquist (github.com/rlinq)
  description: CCA role for handling of Splunk data onboarding
  company: Innovationfleet (github.com/innovationfleet)

  license: MIT

  min_ansible_version: '2.11'
