galaxy_info:
  author: Roger Lindquist (github.com/rlinq)
  description: CCA role for creating the needed settings for the CCA Manager user
  company: Innovationfleet (github.com/innovationfleet)

  license: MIT

  min_ansible_version: '2.11'
