galaxy_info:
  author: Roger Lindquist (github.com/rlinq)
  description: CCA role for handling Splunk user profiles
  company: Innovationfleet (github.com/innovationfleet)

  license: MIT

  min_ansible_version: 2.11
