---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Include and run tasks from external pre bootstrap roles
  ansible.builtin.include_role:
   name: '{{ external_bootstrap_role }}'
  loop_control:
    loop_var: external_bootstrap_role
  loop: '{{ external_bootstrap_pre_roles | default([]) if external_bootstrap_pre_roles | default([]) is iterable else [] }}'

