galaxy_info:
  author: Roger Lindquist (github.com/rlinq)
  description: CCA role for setting up servers with Prerequisites for Splunk Enterprise
  company: Innovationfleet (github.com/innovationfleet)

  license: MIT

  min_ansible_version: 2.11
