---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: AndrÃ© Enemark
#         Roger Lindquist
#
# Release: 2023.1.1

- ansible.builtin.set_fact:
    current_item:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
  with_dict:
    - "{{ secret_type }}"

- name: Generate a random password for pass4SymmKey
  ansible.builtin.set_fact:
    random_pass4SymmKey: "{{ lookup('community.general.random_string', base64=true, length=48) }}"

- ansible.builtin.set_fact:
    tmp_password: "{{ random_pass4SymmKey }}"

- name: Password for {{ current_item.key }}
  ansible.builtin.pause:
    prompt: "Press enter for a new password or enter a 8 character minimum password for {{ secret_type }} ({{tmp_password}})"
  register: password_prompt
  when: not current_item.key | regex_search('default')

- ansible.builtin.set_fact:
    secret_password: "{{ tmp_password if password_prompt.user_input | length == 0 else password_prompt.user_input }}"
  when: not current_item.key | regex_search('default')

- ansible.builtin.set_fact:
    secret_password: 'password'
  when: current_item.key | regex_search('default')

- name: Encrypt the password
  ansible.builtin.command:
    cmd: "python3 {{ role_path }}/../cca.core.splunk/files/bin/splunk_secret_helper.py --splunk-secret {{ splunk_secret }} --cleartext '{{ secret_password }}'"
  register: encrypted_random_secret

- name: Assert that the password encryption command was successful
  ansible.builtin.assert:
    that:
      - encrypted_random_secret.stderr == ''

- name: Vault the secret password
  ansible.builtin.set_fact:
    vaulted_secret_value: >-
      {{ secret_password | vault(lookup('ansible.builtin.file', ansible_env.ANSIBLE_VAULT_PASSWORD_FILE))
      | split() | join('\r\n')
      | regex_replace('1.2;AES256;filter_default', '1.1;AES256') }}

- name: Save the clear text secret as an ansible vault
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: '{{ current_item.key }}_{{ current_item.value }}: !vault "{{ vaulted_secret_value }}"'
    regex: '^{{ current_item.key }}_{{ current_item.value}}:'

- name: Save the secret hash to the file
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: "{{ current_item.key }}_{{ current_item.value }}_hash: '{{ encrypted_random_secret.stdout }}'"
    regex: '^{{ current_item.key }}_{{ current_item.value}}_hash:'
