---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.3.1

- name: Get stat from splunk.secret file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    checksum_algorithm: "sha256"
  register: stat_splunk_secret

- name: Ensure directory path exists for etc/auth
  ansible.builtin.file:
    path: "{{ splunk_path }}/etc/auth"
    state: directory
    mode: '0755'
  when:
    - not stat_splunk_secret.stat.exists

- name: Ensure managed splunk.secret file for new installations
  ansible.builtin.copy:
    content: "{{ cca_splunk_secret }}"
    dest: "{{ splunk_path }}/etc/auth/splunk.secret"
    mode: '0400'
  register: result_splunk_secret_copy
  when:
    - not stat_splunk_secret.stat.exists

- name: Ensure managed splunk.secret file for existing installations
  ansible.builtin.copy:
    content: "{{ cca_splunk_secret }}"
    dest: "{{ splunk_path }}/etc/auth/splunk.secret"
    mode: '0400'
  register: result_splunk_secret_replace
  when:
    - not stat_splunk_secret.stat.exists or
      replace_splunk_secret | default(false)

- name: Get stat from splunk.secret file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    checksum_algorithm: "sha256"
  register: stat_splunk_secret

- name: Assert that the current splunk.secret match the one on the manager host
  ansible.builtin.assert:
    that:
      - stat_splunk_secret.stat.checksum == cca_splunk_secret_sha256
    fail_msg: >-
       The hosts splunk.secret checksum {{ stat_splunk_secret.stat.checksum }} doesn't
       match the expected one stored in CCA {{ cca_splunk_secret_sha256 }}.
       If you like to replace the current one, set replace_splunk_secret variable
       to true when you run the playbook.
  when:
    - manage_splunk_secrets | default(true)
