# Playbook to handle validation
#
# REPO_TYPE=infra
# MENU_DESC=Validate CCA Infrastructure Parameters and files
# EXTRA_VARS=

- name: Initialize playbook run on manager server - Monitoring Consoles
  hosts: manager
  connection: local
  strategy: linear
  any_errors_fatal: true
  vars:
    validate_cca_infrastructure_files: true
  pre_tasks:
    - name: Include initialize task
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          initialize.yml
      vars:
        target: "cca_infastructure_settings"
