---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Robin Blomdahl
#
# Release: 2023.1.1

- name: Ensure firewalld is started
  ansible.builtin.systemd:
    name: firewalld
    state: started
  when:
    - firewall_zone_name is defined
  no_log: "{{ ((cca_verbosity | default(1)) < 3) | bool }}"
